In [3]:
import patsy as pt
import numpy as np
from patsy import dmatrices, dmatrix, demo_data

data=demo_data("a", "b", "x1", "x2", "y", "z column")

In [5]:
demo_data("a")

{'a': ['a1', 'a2', 'a1', 'a2', 'a1', 'a2']}

In [6]:
data

{'a': ['a1', 'a1', 'a2', 'a2', 'a1', 'a1', 'a2', 'a2'],
 'b': ['b1', 'b2', 'b1', 'b2', 'b1', 'b2', 'b1', 'b2'],
 'x1': array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721]),
 'x2': array([-0.10321885,  0.4105985 ,  0.14404357,  1.45427351,  0.76103773,
         0.12167502,  0.44386323,  0.33367433]),
 'y': array([ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982,
         0.6536186 ,  0.8644362 , -0.74216502]),
 'z column': array([ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
         1.46935877,  0.15494743,  0.37816252])}

In [7]:
data['a']

['a1', 'a1', 'a2', 'a2', 'a1', 'a1', 'a2', 'a2']

In [8]:
data['b']

['b1', 'b2', 'b1', 'b2', 'b1', 'b2', 'b1', 'b2']

In [9]:
data['x1']

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721])

In [11]:
data['y']

array([ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982,
        0.6536186 ,  0.8644362 , -0.74216502])

In [13]:
dmatrix("a*b", data)

DesignMatrix with shape (8, 4)
  Intercept  a[T.a2]  b[T.b2]  a[T.a2]:b[T.b2]
          1        0        0                0
          1        0        1                0
          1        1        0                0
          1        1        1                1
          1        0        0                0
          1        0        1                0
          1        1        0                0
          1        1        1                1
  Terms:
    'Intercept' (column 0)
    'a' (column 1)
    'b' (column 2)
    'a:b' (column 3)

In [14]:
dmatrix("a*x1", data)

DesignMatrix with shape (8, 4)
  Intercept  a[T.a2]        x1  a[T.a2]:x1
          1        0   1.76405     0.00000
          1        0   0.40016     0.00000
          1        1   0.97874     0.97874
          1        1   2.24089     2.24089
          1        0   1.86756     0.00000
          1        0  -0.97728    -0.00000
          1        1   0.95009     0.95009
          1        1  -0.15136    -0.15136
  Terms:
    'Intercept' (column 0)
    'a' (column 1)
    'x1' (column 2)
    'a:x1' (column 3)

In [15]:
dmatrix("a:x1", data)

DesignMatrix with shape (8, 3)
  Intercept  a[a1]:x1  a[a2]:x1
          1   1.76405   0.00000
          1   0.40016   0.00000
          1   0.00000   0.97874
          1   0.00000   2.24089
          1   1.86756   0.00000
          1  -0.97728  -0.00000
          1   0.00000   0.95009
          1  -0.00000  -0.15136
  Terms:
    'Intercept' (column 0)
    'a:x1' (columns 1:3)

In [16]:
data['x1']

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721])

In [18]:
outcome, predictors = dmatrices('y ~ x1 + x2', data)

In [19]:
outcome

DesignMatrix with shape (8, 1)
         y
   1.49408
  -0.20516
   0.31307
  -0.85410
  -2.55299
   0.65362
   0.86444
  -0.74217
  Terms:
    'y' (column 0)

In [20]:
np.array(outcome)

array([[ 1.49407907],
       [-0.20515826],
       [ 0.3130677 ],
       [-0.85409574],
       [-2.55298982],
       [ 0.6536186 ],
       [ 0.8644362 ],
       [-0.74216502]])

In [21]:
type(outcome)

patsy.design_info.DesignMatrix

In [22]:
np.array(predictors)

array([[ 1.        ,  1.76405235, -0.10321885],
       [ 1.        ,  0.40015721,  0.4105985 ],
       [ 1.        ,  0.97873798,  0.14404357],
       [ 1.        ,  2.2408932 ,  1.45427351],
       [ 1.        ,  1.86755799,  0.76103773],
       [ 1.        , -0.97727788,  0.12167502],
       [ 1.        ,  0.95008842,  0.44386323],
       [ 1.        , -0.15135721,  0.33367433]])

In [23]:
outcome[0]

array([1.49407907])

In [24]:
predictors[0]

array([ 1.        ,  1.76405235, -0.10321885])

In [32]:
betas = np.linalg.lstsq(predictors, outcome, rcond=None)[0].ravel()

In [34]:
betas

array([ 0.57966234,  0.08859919, -1.76479206])

In [35]:
for name, beta in zip(predictors.design_info.column_names, betas):
    print(f'{name}: {beta}')

Intercept: 0.5796623441231169
x1: 0.08859919035535557
x2: -1.7647920555064998


In [40]:
d = dmatrix('a', data)
type(d), np.array(d)

(patsy.design_info.DesignMatrix, array([[1., 0.],
        [1., 0.],
        [1., 1.],
        [1., 1.],
        [1., 0.],
        [1., 0.],
        [1., 1.],
        [1., 1.]]))

In [41]:
d

DesignMatrix with shape (8, 2)
  Intercept  a[T.a2]
          1        0
          1        0
          1        1
          1        1
          1        0
          1        0
          1        1
          1        1
  Terms:
    'Intercept' (column 0)
    'a' (column 1)

In [52]:
catdata = { 'a': [ 'book', 'pen', 'note', 'water', 'book', 'water', 'water'] }
catdata

{'a': ['book', 'pen', 'note', 'water', 'book', 'water', 'water']}

In [58]:
dm = dmatrix('0 + a', catdata)
dm

DesignMatrix with shape (7, 4)
  a[book]  a[note]  a[pen]  a[water]
        1        0       0         0
        0        0       1         0
        0        1       0         0
        0        0       0         1
        1        0       0         0
        0        0       0         1
        0        0       0         1
  Terms:
    'a' (columns 0:4)

In [57]:
np.array(dm)

array([[1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.]])